name: First Workflow
on: [push]


jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps: 
            - name: echo a string
              run: echo "Hello world"
            - name: Multiline Command
              run: | 
                node -v
                npm -v
    parallerl-job-macos:
        run-on: macos-latest
        steps:
            - name: View SW Version
              run: sw_vers